"use client";

import { motion, useInView, useReducedMotion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { TiltCard } from "@/components/effects/TiltCard";
import { useLocale } from "@/context/LocaleContext";

const LINKS = {
  site: "https://useseal.dev",
  repo: "https://github.com/useseal/seal",
  npm: "https://www.npmjs.com/package/@seal-dev/sdk",
} as const;

const STACK_GROUPS = [
  { label: "API", items: ["Hono", "Drizzle", "PostgreSQL", "Better Auth"] },
  { label: "Web", items: ["Next.js", "React", "TypeScript", "Tailwind"] },
  { label: "Prot", items: ["MCP 2025-11-25", "Streamable HTTP", "stdio"] },
  { label: "Ops", items: ["Stripe", "Vercel", "GitHub Actions", "Vitest"] },
] as const;

const PRACTICES = [
  "MCP proxy intercepts tools/call — agent code unchanged",
  "Bidirectional relay: elicitation + sampling routed back",
  "Declarative policy engine — approval by exception",
  "Hash-chained audit trail, verifiable offline",
  "Open-core: Apache-2.0 local mode, proprietary cloud",
  "Public repo generated by git filter-repo from the monorepo",
  "Releases from tags with npm provenance",
  "Zod at every boundary · no any · no floating promises",
] as const;

/** Fases do gate: chamada → retida → selada → liberada. */
const PHASES = [
  { key: "call", ms: 1150 },
  { key: "held", ms: 1400 },
  { key: "sealed", ms: 1050 },
  { key: "pass", ms: 1250 },
] as const;

const HASHES = ["a17f", "c0d4", "9b2e", "f5a1"] as const;

export function FeaturedSealCard() {
  const { t } = useLocale();
  const containerRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(containerRef, { once: true, margin: "-80px" });
  const reduceMotion = useReducedMotion();
  const [phase, setPhase] = useState(0);
  const [chain, setChain] = useState(1);

  // Loop do gate — só roda quando o card está visível e o usuário aceita movimento.
  useEffect(() => {
    if (!isInView || reduceMotion) return;
    const id = window.setTimeout(() => {
      setPhase((p) => {
        const next = (p + 1) % PHASES.length;
        if (next === 0) setChain((c) => (c % HASHES.length) + 1);
        return next;
      });
    }, PHASES[phase]!.ms);
    return () => window.clearTimeout(id);
  }, [phase, isInView, reduceMotion]);

  const current = reduceMotion ? "sealed" : PHASES[phase]!.key;
  const gateOpen = current === "pass";
  const held = current === "held";
  const stamped = current === "sealed" || current === "pass";
  const visibleChain = reduceMotion ? HASHES.length : chain;

  return (
    <motion.div
      ref={containerRef}
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
    >
      <TiltCard className="overflow-hidden bg-surface relative" intensity={0.22}>
        {/* Animated accent top bar */}
        <motion.div
          className="absolute top-0 left-0 h-[1.5px] bg-accent z-10"
          initial={{ width: 0 }}
          animate={isInView ? { width: "100%" } : { width: 0 }}
          transition={{ duration: 1.4, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
          aria-hidden
        />

        <div className="p-8 sm:p-10 md:p-12">
          {/* Top meta row */}
          <div className="flex items-center justify-between gap-4 mb-7">
            <div className="flex items-center gap-3 flex-wrap">
              <span className="relative flex h-[7px] w-[7px]" aria-hidden>
                <span className="absolute inline-flex h-full w-full rounded-full bg-accent/50 animate-ping" />
                <span className="relative inline-flex h-[7px] w-[7px] rounded-full bg-accent" />
              </span>
              <span className="font-sans text-[8px] tracking-[0.45em] uppercase text-accent/70">
                Open Source
              </span>
              <span className="font-sans text-[8px] tracking-[0.35em] uppercase text-fg-muted/30 pl-2.5 border-l border-fg-muted/15">
                Apache-2.0 · AI Infra
              </span>
            </div>
            <a
              href={LINKS.site}
              target="_blank"
              rel="noopener noreferrer"
              className="font-sans text-[8px] tracking-[0.3em] uppercase text-fg-muted/40 hover:text-accent transition-colors shrink-0"
            >
              useseal.dev ↗
            </a>
          </div>

          {/* Identity */}
          <a
            href={LINKS.site}
            target="_blank"
            rel="noopener noreferrer"
            className="group inline-block"
          >
            <h3 className="font-display text-[clamp(2.6rem,5vw,4rem)] font-light text-fg group-hover:text-accent transition-colors duration-300 tracking-tight leading-[1.0] mb-3">
              Seal
            </h3>
          </a>
          <p className="font-sans text-[8px] tracking-[0.38em] uppercase text-accent/60 mb-5 leading-relaxed">
            Approval-as-an-API — human-in-the-loop as infrastructure
          </p>
          <p className="font-sans text-xs sm:text-sm text-fg-muted leading-[1.9] mb-9 max-w-[56ch]">
            {t("profile.project2.description")}
          </p>

          {/* ━━━ The gate — signature visual ━━━ */}
          <div
            className="relative border border-fg-muted/12 bg-surface-elevated/40 px-4 sm:px-7 py-7 sm:py-8 mb-9"
            aria-hidden
          >
            <span className="absolute top-2 left-3 font-sans text-[7px] tracking-[0.4em] uppercase text-fg-muted/30">
              tools/call
            </span>
            <span className="absolute top-2 right-3 font-sans text-[7px] tracking-[0.4em] uppercase text-accent/50">
              {current === "held" ? "pending" : current === "pass" ? "approved" : "gated"}
            </span>

            <div className="grid grid-cols-[auto_1fr_auto_1fr_auto] items-center gap-2 sm:gap-4 mt-3">
              <GateNode label="Agent" />

              <Track active={current === "call"} reduceMotion={!!reduceMotion} />

              {/* Gate + wax seal */}
              <div className="relative flex flex-col items-center">
                <motion.div
                  className="relative w-11 h-11 sm:w-14 sm:h-14 border border-accent/40 flex items-center justify-center rotate-45"
                  animate={{
                    borderColor: held
                      ? "rgb(var(--color-accent))"
                      : "rgb(var(--color-accent) / 0.4)",
                    scale: held ? 1.06 : 1,
                  }}
                  transition={{ duration: 0.35 }}
                >
                  {/* Gate bars — fecham quando retido, abrem ao liberar */}
                  <motion.span
                    className="absolute left-1/2 top-0 w-px bg-accent/60"
                    animate={{ height: gateOpen ? "0%" : "100%" }}
                    transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
                  />
                  <motion.span
                    className="absolute top-1/2 left-0 h-px bg-accent/60"
                    animate={{ width: gateOpen ? "0%" : "100%" }}
                    transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
                  />
                  {held && (
                    <span className="absolute -inset-1 border border-accent/25 animate-ping" />
                  )}
                </motion.div>

                {/* Wax seal stamp */}
                <motion.div
                  className="absolute -top-3 -right-3 sm:-top-4 sm:-right-4 w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-accent flex items-center justify-center"
                  initial={{ scale: 0, rotate: -28, opacity: 0 }}
                  animate={
                    stamped
                      ? { scale: 1, rotate: -12, opacity: 1 }
                      : { scale: 0, rotate: -28, opacity: 0 }
                  }
                  transition={{ type: "spring", stiffness: 460, damping: 16 }}
                >
                  <span className="font-sans text-[10px] sm:text-xs text-on-accent leading-none">
                    ✓
                  </span>
                </motion.div>

                <span className="font-sans text-[7px] tracking-[0.35em] uppercase text-accent/70 mt-3">
                  Seal
                </span>
              </div>

              <Track active={current === "pass"} reduceMotion={!!reduceMotion} />

              <GateNode label="MCP" />
            </div>

            {/* Hash chain — cresce a cada ciclo aprovado */}
            <div className="flex items-center gap-1.5 mt-7 pt-4 border-t border-fg-muted/10 flex-wrap">
              <span className="font-sans text-[7px] tracking-[0.4em] uppercase text-fg-muted/30 mr-1">
                audit
              </span>
              {HASHES.map((hash, i) => (
                <motion.span
                  key={hash}
                  className="font-sans text-[7px] sm:text-[8px] tracking-[0.18em] text-accent/60 border border-accent/15 px-1.5 py-[2px]"
                  animate={{ opacity: i < visibleChain ? 1 : 0.18 }}
                  transition={{ duration: 0.3 }}
                >
                  {i > 0 && <span className="text-fg-muted/25 mr-1">·</span>}
                  {hash}
                </motion.span>
              ))}
              <span className="font-sans text-[7px] tracking-[0.25em] text-fg-muted/25 ml-1">
                sha-256 chain
              </span>
            </div>
          </div>

          {/* Practices */}
          <div className="space-y-2 mb-8">
            {PRACTICES.map((practice, i) => (
              <motion.div
                key={practice}
                initial={{ opacity: 0, x: -6 }}
                animate={isInView ? { opacity: 1, x: 0 } : {}}
                transition={{ duration: 0.28, delay: 0.55 + i * 0.055 }}
                className="flex items-baseline gap-2.5"
              >
                <span className="font-sans text-[8px] text-accent/45 shrink-0 select-none">›</span>
                <span className="font-sans text-[8px] sm:text-[9px] tracking-[0.12em] text-fg-muted/55 leading-relaxed">
                  {practice}
                </span>
              </motion.div>
            ))}
          </div>

          {/* Stack chips */}
          <div className="border-t border-fg-muted/10 pt-6 space-y-2.5">
            {STACK_GROUPS.map((group, gi) => (
              <div key={group.label} className="flex items-baseline gap-3 flex-wrap">
                <span className="font-sans text-[7px] tracking-[0.4em] uppercase text-fg-muted/30 w-7 shrink-0">
                  {group.label}
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {group.items.map((item, ii) => (
                    <motion.span
                      key={item}
                      initial={{ opacity: 0 }}
                      animate={isInView ? { opacity: 1 } : {}}
                      transition={{ duration: 0.22, delay: 0.85 + gi * 0.08 + ii * 0.035 }}
                      className="font-sans text-[7px] sm:text-[8px] tracking-[0.28em] uppercase text-accent/70 border border-accent/18 px-2 py-[3px]"
                    >
                      {item}
                    </motion.span>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Links */}
          <div className="border-t border-fg-muted/10 mt-6 pt-5 flex flex-wrap gap-x-7 gap-y-2">
            <CardLink href={LINKS.site} label="useseal.dev" />
            <CardLink href={LINKS.repo} label="useseal/seal" />
            <CardLink href={LINKS.npm} label="npm @seal-dev/sdk" />
          </div>
        </div>
      </TiltCard>
    </motion.div>
  );
}

function GateNode({ label }: { label: string }) {
  return (
    <div className="flex flex-col items-center gap-2">
      <span className="w-9 h-9 sm:w-11 sm:h-11 border border-fg-muted/20 flex items-center justify-center">
        <span className="w-1.5 h-1.5 bg-fg-muted/40" />
      </span>
      <span className="font-sans text-[7px] tracking-[0.35em] uppercase text-fg-muted/40">
        {label}
      </span>
    </div>
  );
}

function Track({ active, reduceMotion }: { active: boolean; reduceMotion: boolean }) {
  return (
    <div className="relative h-px bg-fg-muted/15 mb-5">
      {active && !reduceMotion && (
        <motion.span
          className="absolute top-1/2 -translate-y-1/2 w-1.5 h-1.5 bg-accent"
          initial={{ left: "0%", opacity: 0 }}
          animate={{ left: "100%", opacity: [0, 1, 1, 0] }}
          transition={{ duration: 1.05, ease: "linear" }}
        />
      )}
    </div>
  );
}

function CardLink({ href, label }: { href: string; label: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="group font-sans text-[8px] sm:text-[9px] tracking-[0.32em] uppercase text-fg-muted/50 hover:text-accent transition-colors"
    >
      {label}
      <span className="inline-block ml-1.5 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5">
        ↗
      </span>
    </a>
  );
}
